### ISSUE TITLE
Тестовое задание

### ISSUE THREAD

**Issue by matklad** [matklad/minirle#1]
Задача: миниатюрная версия того, чем придётся заниматься на стажировке. 

В этом репозитории находиться μ библиотечка на C для сжатия данных при помощи алгоритма RLE.

API библиотеки находиться в файле minirle.h, реализация -- в файле minirle.c.

Файл test.c содержит некоторое количество тестов. Собрать библиотеку и прогнать тесты можно при помощи команды `make`.

Собственно задание состоит в том, чтобы переписать реализацию minirle.c на Rust, с сохранением такого же бинарного API. Т.е, команда `make` должна компилировать статическую библиотеку на Rust, линковать её с tests.c и запускать получившийся бинарник. Переписывать тесты на Rust не надо. 

При желании можно поменять билд систему с `make`  на что-нибудь другое. Главное, чтобы в итоговом тестовом бинаре оказался код и на Rust, и на C.

Вам помогут документация [Rust](http://rust-lang.github.io/book/first-edition/index.html) и [Cargo](http://doc.crates.io/guide.html).

Вот несколько других интересных экспериментов по портированию С -> Rust:

http://blog.adamperry.me/rust/2016/06/11/baby-steps-porting-musl-to-rust/
https://people.gnome.org/~federico/news-2016-10.html

Просьба не выкладывать своё решение в открытый доступ до конца набора на стажировки :) Решение можно сдавать в виде `.zip` архива мне на почту aleksey.kladov@gmail.com с темой письма "Стажировка 2017".

**Comment by matklad** [comment]
Приём заявок окончен. Всем, кто прислал мне тестовое задание по почте, я ответил (но ещё не проверил все задания).

Если вы посылали задание, но не получили ответ, перепроверьте, что вы постали его на правильный адрес, и напишите ещё раз (можно прямо сюда, чтобы исключить какие-то проблемы с почтой).

**Comment by cithiLoe** [comment]
Задание отправлял, ответа не получил (отправлял с l1ks.sds@gmail.com). Адрес перепроверил, попробовал отправить еще раз.

**Comment by matklad** [comment]
Проверил все присланные мне задания и ответил по email. Результат (прошли ли вы на собеседование) будет известен позднее. 

Самая популярная проблема в решениях: переписать код на C буквально, оставив его в одном большом unsafe блоке. Это не очень хорошо, потому что можно посатить memory safety багу. 

На самом деле, её даже сажать не надо, потому что она уже есть в оригинальном коде (я  не специально :) ). Тут https://github.com/matklad/minirle/blob/master/minirle.c#L16 мы сначала разименовываем `s`, а потом только проверяем, что он in-bounds.
